"""
Agent Service - LangChain/LangGraph agents for test generation and review
"""
import asyncio
import re
import html
import time
from typing import Dict, List, Any, Optional, AsyncGenerator
from langchain_core.messages import HumanMessage, AIMessage, SystemMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder

# Max characters for CodeBeamer context to avoid inflating LLM prompts
MAX_CONTEXT_CHARS = 8000


# System prompts for different agent types
SYSTEM_PROMPTS = {
    "chat": """You are a Knowledge Search assistant for automotive embedded system test automation.
Your primary purpose is to help users find and retrieve information from the project knowledge base.

Key capabilities:
- Search and explain framework resources (Libraries, Keywords, Resources)
- Answer questions about projects, features, and protocols (CAN, UART, DLT, HMI, etc.)
- Look up test patterns and best practices from the knowledge base
- Explain Robot Framework keywords and how to use them
- Reference CodeBeamer test cases and requirements

Always prioritize answers based on the RAG knowledge base context when available.
Be concise, accurate, and include references to source documents when possible.
When referencing CodeBeamer items, always include clickable links.""",

    "test_generator": """You are an expert Robot Framework test automation engineer for HIL (Hardware-in-the-Loop) Automotive Testing.
You specialize in IVI (In-Vehicle Infotainment), Telematics, and embedded system testing.

YOUR TASK: Generate complete, production-ready Robot Framework test scripts (.robot files).

CRITICAL RULES:
1. Generate ONLY valid Robot Framework syntax — no markdown fences, no explanations
2. If RAG knowledge base context is provided, ONLY use keywords that appear in it
3. If no RAG context, use standard Robot Framework built-in keywords
4. Always include proper *** Settings ***, *** Variables ***, and *** Test Cases *** sections
5. Every test case MUST have [Documentation] and [Tags]
6. Use meaningful test case names that describe the test purpose
7. Include proper [Setup] and [Teardown] for resource management
8. Use ${VARIABLE} syntax for configurable values
9. Add comments to explain complex test steps
10. Handle errors gracefully with proper cleanup

STRUCTURE TEMPLATE:
*** Settings ***
Documentation    Suite description
...              Auto-generated by AI Agent Hub
Library          Collections
Library          String
Resource         ../resources/common.resource
Suite Setup      Initialize Test Environment
Suite Teardown   Cleanup Test Environment

*** Variables ***
${TIMEOUT}       30s

*** Test Cases ***
Test Case Name
    [Documentation]    What this test verifies
    [Tags]    tag1    tag2
    [Setup]    Test Specific Setup
    [Teardown]    Test Specific Cleanup
    # Test steps here
    Step Keyword    ${arg1}    ${arg2}
    Verify Result    expected_value

Output ONLY the Robot Framework code. No explanations, no markdown.""",

    "test_reviewer": """You are an expert Robot Framework test code reviewer for automotive embedded systems (HIL, IVI, Telematics).
Review test scripts thoroughly for:

1. **Correctness**: Are test steps logically correct? Do assertions verify the right things?
2. **Completeness**: Are edge cases covered? Missing error scenarios?
3. **Best Practices**: Proper use of [Setup]/[Teardown], variable naming, keyword abstraction
4. **Error Handling**: Graceful cleanup on failure, proper timeout handling
5. **Documentation**: [Documentation] quality, meaningful comments
6. **Style**: Consistent naming, proper indentation (4 spaces), line length
7. **Test Coverage**: Are all requirements covered by test steps?

Provide specific, actionable feedback with corrected code examples.
Format your review as:
- 🔴 **Critical Issues** (must fix)
- 🟡 **Improvements** (should fix)
- 🟢 **Good Practices** (positive feedback)
- 📝 **Suggested Code** (improved version)""",

    "req_tc": """You are an expert test case designer for automotive embedded systems (HIL, IVI, Telematics).
Given a requirement, feature description, or CodeBeamer test case data, generate structured test cases.

Output format — a markdown table:
| TC ID | Test Case Name | Precondition | Test Steps | Expected Result | Priority |
|-------|---------------|--------------|------------|-----------------|----------|

Rules:
1. Generate comprehensive test cases covering normal flow, edge cases, and error scenarios
2. Each test case must have clear, actionable steps
3. Expected results must be specific and measurable
4. Priority: Critical / High / Medium / Low
5. Include both positive and negative test cases
6. Cover boundary values where applicable
7. If RAG context is provided, reference existing test patterns

Generate at least 5-10 test cases per requirement."""
}


class ConversationMemory:
    """Simple conversation memory for agents"""
    
    def __init__(self, max_messages: int = 20):
        self.messages: List[Dict[str, str]] = []
        self.max_messages = max_messages
    
    def add_message(self, role: str, content: str):
        """Add a message to memory"""
        self.messages.append({"role": role, "content": content})
        # Keep only last N messages
        if len(self.messages) > self.max_messages:
            self.messages = self.messages[-self.max_messages:]
    
    def get_messages(self) -> List[Dict[str, str]]:
        """Get all messages"""
        return self.messages.copy()
    
    def clear(self):
        """Clear memory"""
        self.messages = []


class AgentService:
    """Main agent service using LangChain patterns"""
    
    def __init__(self):
        self.memories: Dict[str, ConversationMemory] = {}
        self.system_prompts = SYSTEM_PROMPTS
        self._llm_service = None
    
    @property
    def llm_service(self):
        if self._llm_service is None:
            from services.llm_service import llm_service
            self._llm_service = llm_service
        return self._llm_service
    
    def get_or_create_memory(self, session_id: str) -> ConversationMemory:
        """Get or create conversation memory for a session"""
        if session_id not in self.memories:
            self.memories[session_id] = ConversationMemory()
        return self.memories[session_id]
    
    @staticmethod
    def _extract_item_ids(message: str) -> List[int]:
        """Extract CodeBeamer item IDs from user message.
        Detects patterns: TCID-123, TC-123, tcid: 123, #123, item 123, test case 123
        """
        patterns = [
            r'(?:TCID|TC)[\s:\-#]*(\d+)',        # TCID-123, TC:123, tcid: 123
            r'#(\d+)',                             # #123
            r'item[\s:\-#]*(\d+)',                 # item 123, item-123, item: 123
            r'test\s*case[\s:\-#]*(\d+)',          # test case 123, test case: 123
        ]
        ids = set()
        for pattern in patterns:
            for match in re.finditer(pattern, message, re.IGNORECASE):
                item_id = int(match.group(1))
                if item_id > 0:
                    ids.add(item_id)
        return sorted(ids)
    
    @staticmethod
    def _format_item_as_context(item: Dict[str, Any]) -> str:
        """Format a CodeBeamer item into readable context for the LLM"""
        lines = []
        item_id = item.get('id', 'N/A')
        name = item.get('name', 'Untitled')
        lines.append(f"=== Test Case #{item_id}: {name} ===")
        
        # CodeBeamer direct link
        try:
            from config import settings
            if settings.codebeamer_url:
                cb_base = settings.codebeamer_url.rstrip('/')
                # Remove trailing /cb if present to avoid double /cb/cb/
                if cb_base.endswith('/cb'):
                    cb_base = cb_base[:-3]
                cb_link = f"{cb_base}/cb/item/{item_id}"
                lines.append(f"CodeBeamer Link: {cb_link}")
        except Exception:
            pass
        
        # Status
        status = item.get('status', {})
        if isinstance(status, dict):
            lines.append(f"Status: {status.get('name', 'N/A')}")
        
        # Tracker info
        tracker = item.get('tracker', {})
        if isinstance(tracker, dict) and tracker.get('name'):
            lines.append(f"Tracker: {tracker.get('name')}")
        
        # Description
        desc = item.get('description', '')
        if desc:
            # Strip HTML tags for readability
            clean_desc = re.sub(r'<[^>]+>', '', str(desc))
            clean_desc = html.unescape(clean_desc).strip()
            if clean_desc:
                lines.append(f"Description:\n{clean_desc}")
        
        # Custom fields - look for common test case fields
        custom_fields = item.get('customFields', []) or []
        for field in custom_fields:
            if isinstance(field, dict):
                field_name = field.get('name', '') or field.get('fieldId', '')
                field_value = field.get('value', '') or field.get('values', '')
                if field_name and field_value:
                    if isinstance(field_value, str):
                        field_value = re.sub(r'<[^>]+>', '', field_value)
                        field_value = html.unescape(field_value).strip()
                    lines.append(f"{field_name}: {field_value}")
        
        # Pre/Post actions (test case specific)
        for key in ['preAction', 'postAction', 'testSteps', 'expectedResult']:
            value = item.get(key)
            if value:
                if isinstance(value, str):
                    value = re.sub(r'<[^>]+>', '', value)
                    value = html.unescape(value).strip()
                if isinstance(value, list):
                    for i, step in enumerate(value, 1):
                        if isinstance(step, dict):
                            action = step.get('action', step.get('description', ''))
                            expected = step.get('expectedResult', '')
                            if action:
                                action = re.sub(r'<[^>]+>', '', str(action))
                                action = html.unescape(action).strip()
                            if expected:
                                expected = re.sub(r'<[^>]+>', '', str(expected))
                                expected = html.unescape(expected).strip()
                            step_text = f"  Step {i}: {action}"
                            if expected:
                                step_text += f" → Expected: {expected}"
                            lines.append(step_text)
                        else:
                            lines.append(f"  Step {i}: {step}")
                elif value:
                    label = key.replace('_', ' ').title()
                    lines.append(f"{label}: {value}")
        
        return "\n".join(lines)
    
    async def _fetch_codebeamer_context(self, item_ids: List[int]) -> str:
        """Fetch CodeBeamer items and format as context string (async-safe)"""
        from services.codebeamer_service import get_codebeamer_service
        
        service = get_codebeamer_service()
        if not service:
            return ""
        
        context_parts = []
        for item_id in item_ids[:5]:  # Limit to 5 items to avoid huge context
            # Use async wrapper to avoid blocking the event loop
            item = await service.get_item_async(item_id)
            if item:
                context_parts.append(self._format_item_as_context(item))
            else:
                context_parts.append(f"=== Item #{item_id}: Not found or access denied ===")
        
        if context_parts:
            return "\n\n--- CodeBeamer Test Case Data ---\n\n" + "\n\n".join(context_parts)
        return ""
    
    async def _fetch_projects_context(self) -> str:
        """Fetch list of CodeBeamer projects (async-safe)"""
        from services.codebeamer_service import get_codebeamer_service
        
        service = get_codebeamer_service()
        if not service:
            return "\n--- CodeBeamer ---\nCodeBeamer is not configured. Please configure it in the Config tab."
        
        result = await service.list_projects_async(page_size=50)
        if isinstance(result, dict) and result.get('error'):
            return f"\n--- CodeBeamer ---\nFailed to fetch projects: {result.get('message', 'Unknown error')}"
        
        projects = []
        items = result if isinstance(result, list) else result.get('projects', result.get('items', []))
        if isinstance(items, list):
            for p in items:
                if isinstance(p, dict):
                    pid = p.get('id', 'N/A')
                    name = p.get('name', 'Untitled')
                    desc = p.get('description', '')
                    if desc and isinstance(desc, str):
                        desc = re.sub(r'<[^>]+>', '', desc).strip()[:100]
                    projects.append(f"- Project #{pid}: {name}" + (f" — {desc}" if desc else ""))
        
        if projects:
            return "\n--- CodeBeamer Projects ---\n" + "\n".join(projects)
        return "\n--- CodeBeamer ---\nNo projects found."
    
    async def _fetch_tracker_context(self, tracker_id: int) -> str:
        """Fetch items from a CodeBeamer tracker (async-safe)"""
        from services.codebeamer_service import get_codebeamer_service
        
        service = get_codebeamer_service()
        if not service:
            return ""
        
        result = await service.get_tracker_items_async(tracker_id, max_items=20)
        if isinstance(result, dict) and result.get('error'):
            return f"\n--- Tracker #{tracker_id} ---\nFailed: {result.get('message', 'Unknown error')}"
        
        items = result.get('items', result.get('itemRefs', []))
        if not items:
            return f"\n--- Tracker #{tracker_id} ---\nNo items found."
        
        lines = [f"--- Tracker #{tracker_id}: {len(items)} items ---"]
        for item in items[:20]:
            iid = item.get('id', 'N/A')
            name = item.get('name', 'Untitled')
            status = item.get('status', {})
            status_name = status.get('name', '') if isinstance(status, dict) else ''
            lines.append(f"- #{iid}: {name}" + (f" [{status_name}]" if status_name else ""))
        return "\n".join(lines)
    
    @staticmethod
    def _detect_codebeamer_queries(message: str) -> Dict[str, Any]:
        """Detect CodeBeamer-related queries beyond just TCID lookups"""
        msg_lower = message.lower()
        queries = {}
        
        # Detect project listing request
        if any(kw in msg_lower for kw in ['list project', 'show project', 'all project', 
                                           'available project', 'codebeamer project']):
            queries['list_projects'] = True
        
        # Detect tracker query
        tracker_match = re.search(r'tracker[\s:#-]*(\d+)', msg_lower)
        if tracker_match:
            queries['tracker_id'] = int(tracker_match.group(1))
        
        return queries

    @staticmethod
    def _sanitize_messages(messages: List[Dict[str, str]]) -> List[Dict[str, str]]:
        """
        Sanitize messages before sending to LLM:
        - Remove empty content messages
        - Ensure system message is at index 0 only
        - Ensure proper alternating user/assistant pattern
        - Merge consecutive same-role messages
        """
        if not messages:
            return messages

        # 1. Remove messages with empty/None content
        messages = [m for m in messages if m.get("content", "").strip()]

        # 2. Separate system from rest
        system_msgs = [m for m in messages if m["role"] == "system"]
        non_system = [m for m in messages if m["role"] != "system"]

        # 3. Merge all system messages into one at position 0
        result = []
        if system_msgs:
            combined_system = "\n\n".join(m["content"] for m in system_msgs)
            result.append({"role": "system", "content": combined_system})

        # 4. Fix alternating pattern for non-system messages
        # Merge consecutive same-role messages, drop leading assistant messages
        fixed = []
        for msg in non_system:
            role = msg["role"]
            if role not in ("user", "assistant"):
                continue
            if fixed and fixed[-1]["role"] == role:
                # Merge with previous same-role message
                fixed[-1]["content"] += "\n\n" + msg["content"]
            else:
                fixed.append({"role": role, "content": msg["content"]})

        # 5. Drop leading assistant message (must start with user)
        while fixed and fixed[0]["role"] == "assistant":
            fixed.pop(0)

        result.extend(fixed)
        return result

    async def _build_messages_async(
        self,
        agent_type: str,
        user_message: str,
        session_id: Optional[str] = None,
        context: Optional[str] = None,
        use_rag: bool = True,
    ) -> List[Dict[str, str]]:
        """Build message list for LLM (async - fetches CodeBeamer data without blocking)"""
        messages = []
        
        # Add system prompt
        system_prompt = self.system_prompts.get(agent_type, self.system_prompts["chat"])
        if context:
            system_prompt += f"\n\nContext:\n{context}"
        
        # Auto-fetch CodeBeamer data based on user message (works for all agent types)
        cb_parts = []
        
        # 1. Check for item IDs (TCID, TC, #id, etc.)
        item_ids = self._extract_item_ids(user_message)
        if item_ids:
            print(f"[CodeBeamer] Detected item IDs: {item_ids}")
            t0 = time.time()
            cb_context = await self._fetch_codebeamer_context(item_ids)
            elapsed = time.time() - t0
            print(f"[CodeBeamer] Context fetch took {elapsed:.2f}s")
            if cb_context:
                cb_parts.append(cb_context)
            else:
                print("[CodeBeamer] No context returned (service not configured or items not found)")
        
        # 2. Check for other CodeBeamer queries (chat only)
        if agent_type == "chat":
            queries = self._detect_codebeamer_queries(user_message)
            if queries.get('list_projects'):
                print("[CodeBeamer] Fetching projects list")
                cb_parts.append(await self._fetch_projects_context())
            if queries.get('tracker_id'):
                tid = queries['tracker_id']
                print(f"[CodeBeamer] Fetching tracker #{tid}")
                cb_parts.append(await self._fetch_tracker_context(tid))
        
        # Inject all CodeBeamer data (with size limit)
        if cb_parts:
            all_context = "\n\n".join(cb_parts)
            
            # Truncate if context is too large to avoid slow LLM responses
            if len(all_context) > MAX_CONTEXT_CHARS:
                print(f"[CodeBeamer] Truncating context from {len(all_context)} to {MAX_CONTEXT_CHARS} chars")
                all_context = all_context[:MAX_CONTEXT_CHARS] + "\n\n... (context truncated for performance)"
            
            print(f"[CodeBeamer] Injecting context ({len(all_context)} chars) for agent: {agent_type}")
            if agent_type == "test_generator":
                system_prompt += f"\n{all_context}\n\nUse the above CodeBeamer test case data (pre-conditions, test steps, expected results) to generate the Robot Framework test code."
            elif agent_type == "test_reviewer":
                system_prompt += f"\n{all_context}\n\nUse the above CodeBeamer test case data as reference when reviewing the test code."
            elif agent_type == "req_tc":
                system_prompt += f"\n{all_context}\n\nUse the above CodeBeamer data to generate structured test cases covering all requirements and test steps."
            else:
                system_prompt += f"\n{all_context}\n\nUse the above CodeBeamer data to answer the user's question accurately. Focus on background information (name, status, description, test steps, expected results). Format the information clearly. IMPORTANT: Always include the CodeBeamer Link at the very end of your response as a clickable markdown hyperlink like: 🔗 **CodeBeamer Link**: [Test Case #ID](url)"
        
        # Auto-fetch RAG context from knowledge base (only if use_rag is True)
        if use_rag:
            try:
                from services.rag_service import get_rag_service
                rag = get_rag_service()
                if rag:
                    # Use hybrid search (vector + BM25) for better recall
                    rag_context = await rag.search_formatted_hybrid_async(user_message, top_k=5, alpha=0.7)
                    if rag_context:
                        print(f"[RAG] Injecting hybrid context ({len(rag_context)} chars) for agent: {agent_type}")
                        system_prompt += f"\n\n{rag_context}\n\nUse the above knowledge base information to help answer the user's question when relevant."
            except Exception as e:
                print(f"[RAG] Context fetch error: {e}")
        else:
            print(f"[RAG] Skipped (use_rag=False)")
        
        messages.append({"role": "system", "content": system_prompt})
        
        # Add conversation history if session exists
        if session_id:
            memory = self.get_or_create_memory(session_id)
            messages.extend(memory.get_messages())
        
        # Add current user message
        messages.append({"role": "user", "content": user_message})

        # Sanitize before returning (fix alternation, remove empty, reorder system)
        messages = self._sanitize_messages(messages)

        return messages
    
    async def chat(
        self,
        message: str,
        session_id: str,
        context: Optional[str] = None,
        use_rag: bool = True,
        mode: str = "chat",
    ) -> str:
        """General chat with conversation memory (supports mode & RAG toggle)"""
        messages = await self._build_messages_async(mode, message, session_id, context, use_rag=use_rag)
        
        # Get response
        response = await self.llm_service.chat(messages)
        
        # Update memory
        memory = self.get_or_create_memory(session_id)
        memory.add_message("user", message)
        memory.add_message("assistant", response)
        
        return response
    
    async def stream_chat(
        self,
        message: str,
        session_id: str,
        context: Optional[str] = None,
        use_rag: bool = True,
        mode: str = "chat",
    ) -> AsyncGenerator[str, None]:
        """Stream chat response (supports mode & RAG toggle)"""
        messages = await self._build_messages_async(mode, message, session_id, context, use_rag=use_rag)

        memory = self.get_or_create_memory(session_id)
        full_response = ""
        try:
            async for chunk in self.llm_service.stream_chat(messages):
                full_response += chunk
                yield chunk
        finally:
            # Always save to memory — even partial responses from aborted streams.
            # Skip only if absolutely nothing was returned (avoids empty assistant msgs).
            memory.add_message("user", message)
            if full_response.strip():
                memory.add_message("assistant", full_response)
    
    async def generate_test(
        self,
        test_case_description: str,
        test_type: str = "generic",
        additional_context: Optional[str] = None
    ) -> str:
        """Generate Robot Framework test from description"""
        context = f"""
Test Type: {test_type}
{f'Additional Context: {additional_context}' if additional_context else ''}
"""
        messages = await self._build_messages_async("test_generator", test_case_description, context=context)
        return await self.llm_service.chat(messages)
    
    async def review_test(
        self,
        test_code: str,
        focus_areas: Optional[List[str]] = None
    ) -> str:
        """Review and provide feedback on test code"""
        focus = ""
        if focus_areas:
            focus = f"\nFocus on these areas: {', '.join(focus_areas)}"
        
        prompt = f"""Please review this Robot Framework test:{focus}

```robot
{test_code}
```

Provide specific feedback on issues and improvements."""
        
        messages = await self._build_messages_async("test_reviewer", prompt)
        return await self.llm_service.chat(messages)
    
    async def improve_test(
        self,
        test_code: str,
        improvement_request: str
    ) -> str:
        """Improve test code based on request"""
        prompt = f"""Improve this Robot Framework test based on the following request:

Request: {improvement_request}

Original test:
```robot
{test_code}
```

Output ONLY the improved Robot Framework code."""
        
        messages = await self._build_messages_async("test_generator", prompt)
        return await self.llm_service.chat(messages)
    
    def clear_session(self, session_id: str):
        """Clear session memory"""
        if session_id in self.memories:
            self.memories[session_id].clear()
    
    def get_session_history(self, session_id: str) -> List[Dict[str, str]]:
        """Get session conversation history"""
        if session_id in self.memories:
            return self.memories[session_id].get_messages()
        return []


# Global instance
agent_service = AgentService()
