"""
Test Generator Service - Generate Robot Framework tests for automotive embedded systems
Supports: CAN, UART, DLT, HMI testing
"""
from typing import Dict, List, Any, Optional
from datetime import datetime


# Robot Framework templates for automotive embedded system testing
ROBOT_TEMPLATES = {
    "header": '''*** Settings ***
Documentation    {documentation}
...              Generated by AI Automation Hub on {timestamp}

Library          Collections
Library          String
{libraries}

Resource         {resource_path}

*** Variables ***
{variables}

''',

    "can_test": '''*** Test Cases ***
{test_name}
    [Documentation]    {description}
    [Tags]    CAN    {tags}
    
    # Setup CAN communication
    Initialize CAN Interface    ${{CAN_INTERFACE}}    ${{CAN_BAUDRATE}}
    
    # Send CAN message
    ${{msg_id}}=    Set Variable    {message_id}
    ${{msg_data}}=    Create List    {message_data}
    Send CAN Message    ${{msg_id}}    ${{msg_data}}
    
    # Wait and verify response
    Sleep    ${{CAN_RESPONSE_TIMEOUT}}
    ${{response}}=    Receive CAN Message    ${{msg_id}}
    Should Not Be Empty    ${{response}}
    {verification_steps}
    
    # Cleanup
    Close CAN Interface

''',

    "uart_test": '''*** Test Cases ***
{test_name}
    [Documentation]    {description}
    [Tags]    UART    {tags}
    
    # Setup UART communication
    Open Serial Port    ${{UART_PORT}}    ${{UART_BAUDRATE}}
    
    # Send command
    ${{command}}=    Set Variable    {command}
    Send Serial Data    ${{command}}
    
    # Wait for response
    Sleep    ${{UART_RESPONSE_TIMEOUT}}
    ${{response}}=    Read Serial Data
    
    # Verify response
    Should Contain    ${{response}}    {expected_response}
    {verification_steps}
    
    # Cleanup
    Close Serial Port

''',

    "dlt_test": '''*** Test Cases ***
{test_name}
    [Documentation]    {description}
    [Tags]    DLT    Logging    {tags}
    
    # Start DLT logging
    Start DLT Daemon    ${{DLT_CONFIG}}
    Connect To DLT    ${{DLT_HOST}}    ${{DLT_PORT}}
    
    # Trigger action and capture logs
    {trigger_action}
    Sleep    ${{DLT_CAPTURE_TIMEOUT}}
    
    # Get and verify DLT messages
    ${{dlt_messages}}=    Get DLT Messages    app_id=${{APP_ID}}    context_id=${{CONTEXT_ID}}
    Should Not Be Empty    ${{dlt_messages}}
    
    # Verify log content
    {verification_steps}
    
    # Cleanup
    Stop DLT Logging
    Disconnect From DLT

''',

    "hmi_test": '''*** Test Cases ***
{test_name}
    [Documentation]    {description}
    [Tags]    HMI    UI    {tags}
    
    # Initialize HMI test environment
    Initialize HMI    ${{HMI_CONFIG}}
    
    # Navigate to screen
    Navigate To Screen    {screen_name}
    Wait Until Screen Loaded    {screen_name}
    
    # Perform HMI interactions
    {interaction_steps}
    
    # Verify HMI state
    {verification_steps}
    
    # Capture screenshot for verification
    Capture HMI Screenshot    {test_name}_result.png
    
    # Cleanup
    Close HMI

''',

    "generic_test": '''*** Test Cases ***
{test_name}
    [Documentation]    {description}
    [Tags]    {tags}
    
    # Test Setup
    Log    Starting test: {test_name}
    
    # Test Steps
    {test_steps}
    
    # Verification
    {verification_steps}
    
    # Test Cleanup
    Log    Test completed: {test_name}

'''
}


class TestGeneratorService:
    """Generate Robot Framework tests for automotive embedded systems"""
    
    def __init__(self):
        self.templates = ROBOT_TEMPLATES
        self.default_libraries = [
            "CANLibrary",
            "SerialLibrary", 
            "DLTLibrary",
            "HMILibrary"
        ]
    
    def generate_test(
        self,
        test_type: str,
        test_name: str,
        description: str,
        parameters: Dict[str, Any],
        libraries: Optional[List[str]] = None,
        resource_path: str = "common_resources.robot",
        tags: Optional[List[str]] = None
    ) -> str:
        """Generate a Robot Framework test based on type"""
        
        libs = libraries or []
        tag_str = "    ".join(tags or [])
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Generate header
        library_imports = "\n".join([f"Library          {lib}" for lib in libs])
        variables = self._generate_variables(test_type, parameters)
        
        header = self.templates["header"].format(
            documentation=description,
            timestamp=timestamp,
            libraries=library_imports,
            resource_path=resource_path,
            variables=variables
        )
        
        # Generate test case based on type
        test_type_lower = test_type.lower()
        
        if test_type_lower == "can":
            test_body = self._generate_can_test(test_name, description, parameters, tag_str)
        elif test_type_lower == "uart":
            test_body = self._generate_uart_test(test_name, description, parameters, tag_str)
        elif test_type_lower == "dlt":
            test_body = self._generate_dlt_test(test_name, description, parameters, tag_str)
        elif test_type_lower == "hmi":
            test_body = self._generate_hmi_test(test_name, description, parameters, tag_str)
        else:
            test_body = self._generate_generic_test(test_name, description, parameters, tag_str)
        
        return header + test_body
    
    def _generate_variables(self, test_type: str, parameters: Dict[str, Any]) -> str:
        """Generate Robot Framework variables section"""
        variables = []
        
        if test_type.lower() == "can":
            variables.extend([
                "${CAN_INTERFACE}    can0",
                "${CAN_BAUDRATE}    500000",
                "${CAN_RESPONSE_TIMEOUT}    1s"
            ])
        elif test_type.lower() == "uart":
            variables.extend([
                "${UART_PORT}    /dev/ttyUSB0",
                "${UART_BAUDRATE}    115200",
                "${UART_RESPONSE_TIMEOUT}    2s"
            ])
        elif test_type.lower() == "dlt":
            variables.extend([
                "${DLT_HOST}    localhost",
                "${DLT_PORT}    3490",
                "${DLT_CONFIG}    dlt.conf",
                "${DLT_CAPTURE_TIMEOUT}    5s",
                "${APP_ID}    APP1",
                "${CONTEXT_ID}    CTX1"
            ])
        elif test_type.lower() == "hmi":
            variables.extend([
                "${HMI_CONFIG}    hmi_config.json",
                "${HMI_TIMEOUT}    10s"
            ])
        
        # Add custom parameters
        for key, value in parameters.items():
            if key.startswith("var_"):
                var_name = key[4:].upper()
                variables.append(f"${{{var_name}}}    {value}")
        
        return "\n".join(variables)
    
    def _generate_can_test(self, test_name: str, description: str, params: Dict, tags: str) -> str:
        """Generate CAN communication test"""
        return self.templates["can_test"].format(
            test_name=test_name,
            description=description,
            tags=tags,
            message_id=params.get("message_id", "0x123"),
            message_data=params.get("message_data", "0x01    0x02    0x03"),
            verification_steps=params.get("verification", "Log    Response received")
        )
    
    def _generate_uart_test(self, test_name: str, description: str, params: Dict, tags: str) -> str:
        """Generate UART protocol test"""
        return self.templates["uart_test"].format(
            test_name=test_name,
            description=description,
            tags=tags,
            command=params.get("command", "AT"),
            expected_response=params.get("expected_response", "OK"),
            verification_steps=params.get("verification", "Log    Response verified")
        )
    
    def _generate_dlt_test(self, test_name: str, description: str, params: Dict, tags: str) -> str:
        """Generate DLT logging test"""
        return self.templates["dlt_test"].format(
            test_name=test_name,
            description=description,
            tags=tags,
            trigger_action=params.get("trigger_action", "Log    Triggering test action"),
            verification_steps=params.get("verification", "Log    DLT messages verified")
        )
    
    def _generate_hmi_test(self, test_name: str, description: str, params: Dict, tags: str) -> str:
        """Generate HMI interaction test"""
        return self.templates["hmi_test"].format(
            test_name=test_name,
            description=description,
            tags=tags,
            screen_name=params.get("screen_name", "MainScreen"),
            interaction_steps=params.get("interaction", "Click Element    ${BUTTON_ID}"),
            verification_steps=params.get("verification", "Element Should Be Visible    ${RESULT_ELEMENT}")
        )
    
    def _generate_generic_test(self, test_name: str, description: str, params: Dict, tags: str) -> str:
        """Generate generic test"""
        return self.templates["generic_test"].format(
            test_name=test_name,
            description=description,
            tags=tags,
            test_steps=params.get("steps", "Log    Executing test steps"),
            verification_steps=params.get("verification", "Log    Verification complete")
        )
    
    def get_available_templates(self) -> List[str]:
        """Get list of available test types"""
        return ["CAN", "UART", "DLT", "HMI", "Generic"]
    
    def validate_test(self, test_content: str) -> Dict[str, Any]:
        """Validate generated Robot Framework test syntax"""
        issues = []
        warnings = []
        
        # Check for required sections
        if "*** Settings ***" not in test_content:
            issues.append("Missing *** Settings *** section")
        if "*** Test Cases ***" not in test_content:
            issues.append("Missing *** Test Cases *** section")
        
        # Check for proper indentation
        lines = test_content.split('\n')
        for i, line in enumerate(lines):
            if line.strip() and not line.startswith('*') and not line.startswith(' ') and not line.startswith('\t'):
                if not line.startswith('#') and not line.startswith('['):
                    if i > 0 and '*** Test Cases ***' in '\n'.join(lines[:i]):
                        # Inside test cases, keywords should be indented
                        if not any(line.startswith(kw) for kw in ['[Documentation]', '[Tags]', '[Setup]', '[Teardown]']):
                            warnings.append(f"Line {i+1} may need indentation: {line[:50]}")
        
        return {
            "valid": len(issues) == 0,
            "issues": issues,
            "warnings": warnings
        }


# Global instance
test_generator = TestGeneratorService()
